apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    jsonData:
      maxLines: 5000
      derivedFields:
        - name: correlationId
          matcherRegex: '"correlationId"\s*:\s*"([^"]+)"'
          url: '/explore?left=%7B%22datasource%22:%22Loki%22,%22queries%22:%5B%7B%22expr%22:%22%7Bapp%3D%5C%22reapp-back%5C%22%7D+%7C+json+%7C+correlationId%3D%5C%22${__value.raw}%5C%22%22%7D%5D%7D'
          urlDisplayLabel: 'View full trace'
